"""empty message

Revision ID: e0c7ede59dea
Revises: 375c1e662f92
Create Date: 2022-06-06 13:32:57.340000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e0c7ede59dea'
down_revision = '375c1e662f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'phone',
                    existing_type=sa.VARCHAR(length=120),
                    type_=sa.String(length=20),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'phone',
                    existing_type=sa.String(length=20),
                    type_=sa.VARCHAR(length=120),
                    existing_nullable=False)
    # ### end Alembic commands ###
